# Dependabot configuration for automated dependency updates
# This configuration handles Rust dependencies and GitHub Actions updates
# with settings optimized for long-term maintenance and automatic merging

version: 2

updates:
  # ============================================================================
  # Cargo (Rust) Dependencies
  # ============================================================================
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    
    # Commit message configuration for semantic versioning
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
      include: "scope"
    
    # Auto-merge configuration
    open-pull-requests-limit: 10
    target-branch: "main"
    
    # Reviewers and assignees (configure with your GitHub usernames)
    reviewers:
      - "oxyzenQ"
    assignees:
      - "oxyzenQ"
    
    # Labels for organization and automation
    labels:
      - "dependencies"
      - "rust"
      - "auto-merge"
    
    # Grouping strategy for cleaner PRs
    groups:
      # Group all patch updates together
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      
      # Group minor updates together
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
      
      # Group development dependencies
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"
    
    # Version update strategy
    versioning-strategy: "increase"
    
    # Allow both direct and indirect dependencies
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    
    # Ignore specific dependencies (add as needed)
    # ignore:
    #   - dependency-name: "sysinfo"
    #     update-types: ["version-update:semver-major"]

  # ============================================================================
  # GitHub Actions Dependencies
  # ============================================================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    
    # Commit message configuration
    commit-message:
      prefix: "ci"
      include: "scope"
    
    # Auto-merge configuration
    open-pull-requests-limit: 5
    target-branch: "main"
    
    # Reviewers and assignees
    reviewers:
      - "oxyzenQ"
    assignees:
      - "oxyzenQ"
    
    # Labels for organization
    labels:
      - "dependencies"
      - "github-actions"
      - "auto-merge"
    
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - "*"

# ============================================================================
# INSTRUCTIONS FOR AUTO-MERGE SETUP
# ============================================================================
# 
# To enable automatic merging to main branch, you need to:
#
# 1. Enable auto-merge in repository settings:
#    - Go to: Settings > General > Pull Requests
#    - Check "Allow auto-merge"
#
# 2. Set up branch protection rules (optional but recommended):
#    - Go to: Settings > Branches > Branch protection rules
#    - Add rule for "main" branch
#    - Enable: "Require status checks to pass before merging"
#    - Select required CI checks (e.g., "ci", "test")
#
# 3. Create a GitHub Actions workflow for auto-merge:
#    - See the auto-merge workflow in .github/workflows/dependabot-auto-merge.yml
#
# 4. Grant Dependabot permissions:
#    - Go to: Settings > Code security and analysis > Dependabot
#    - Enable "Dependabot security updates"
#    - Enable "Dependabot version updates"
#
# 5. Configure secrets (if needed):
#    - Go to: Settings > Secrets and variables > Actions
#    - Add PAT token with appropriate permissions
#
# ============================================================================
