# cargo-deny policy for Lyvoxa (GPL-3.0 project)
# Updated for modern cargo-deny schema

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
]

[advisories]
# Ignore specific advisories by ID
ignore = []

[licenses]
# Only allow GPLv3-compatible and permissive licenses
allow = [
  "GPL-3.0-only",
  "GPL-3.0-or-later",
  "MIT",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-DFS-2016"
]
# Confidence threshold for license detection
confidence-threshold = 0.8

[bans]
# Warn on multiple versions but don't fail the build
multiple-versions = "warn"
# Wildcard dependencies are often a mistake
wildcards = "allow"

# Deny specific crates
[[bans.deny]]
name = "users"
reason = "RUSTSEC-2025-0040; unmaintained and vulnerable"

[sources]
# Only allow crates.io
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
