# OpenSSF Scorecard workflow
# Schedules weekly scans and on-push validations, publishes results to Scorecards and Code Scanning
name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 06:00 UTC
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write           # Required for uploading results to OpenSSF
  security-events: write    # Required for SARIF upload to code scanning

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard analysis
        uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload results to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
